resource "local_file" "pet" {

    filename = var.filename
    //content = var.content
    content = "my favourite pet is ${random_pet.my-pet.id}" //interpolation
}

resource "random_pet" "my-pet" {
    prefix = var.prefix
    separator = var.separator
    length = var.length
  
}

//output variable

output "pet_name" {
    value = random_pet.my-pet.id
    description = "Record the value of pet  ID generated by the random_pet resource"
  
}